### ISSUE TITLE
please add token type "symbol"

### ISSUE THREAD

**Issue by inithink** [automock/automock#182]
I find your project really useful :)

Currently, tokens can use string, but it would be nice if symbols were also supported :)

thank you

**Comment by omermorad** [comment]
Hello @inithink

Very happy to hear, thank you 😄

What exact version of Automock are you working with? Because, yes, we didn't provide the ability to add symbols until version 2.0.

**Comment by inithink** [comment]
Oh. I missed it. Confirmed that symbol is supported. I will close this issue ^^;;
