### ISSUE TITLE
Get dependency via string token with TypeDI

### ISSUE THREAD

**Issue by GeekEast** [automock/automock#53]
Hi,
I have one class with injectables but via string token as bellow.

```typescript
class UserRepo {
   constructor(@Inject("ddb") private readonly dynamodbClient: DynamoDB){}
}
```

But in the test file, when I try to get the dependency via string token, it seems not to work

```typescript
   const {unit, unitRef: container} = TestBed.create(UserRepo).compile()
   // this line doesn't work
   const client = container.get("ddb")
```

Is there solution this kind of use case? Thanks!

**Comment by omermorad** [comment]
Hi @GeekEast,

Thanks for reaching out. To better understand the problem and provide a suitable solution, could you please provide some more information?

1. Which version of Automock are you currently using?
2. What version of Node.js are you using?
3. Which Dependency Injection (DI) framework are you utilizing in your project?

If you could also share the relevant setup code from your test file where you are trying to retrieve the dependency using the string token, it would greatly assist in reproducing the issue and finding a resolution.

**Comment by omermorad** [comment]
I see.

In version 1.x of Automock, the primary focus was on supporting NestJS, and we acknowledge that there may be limitations when using it with other frameworks or DI containers like TypeDI.

In the meantime, you can try using the following workaround to overcome the issue:

```typescript
class DynamodbClient {
   constructor(@Inject("ddb") public readonly client: DynamoDB) {}
}

class UserRepo {
   constructor(private readonly dynamodbClient: DynamodbClient) {}

   someMethod() {
      const myClient = this.dynamodbClient.client;
      // Rest of your code
   }
}
```

While this workaround may not be the ideal solution, I want to assure you that we are actively working on Automock 2.0, which is scheduled to be released shortly. In Automock 2.0, we have made significant improvements and enhancements, including full support for TypeDI. I believe that this upcoming release will address the issue you encountered and provide a seamless integration experience with TypeDI.

If you have any further questions or need assistance, please don't hesitate to let me know!

**Comment by GeekEast** [comment]
Thanks @omermorad glad to see it will be supported in version 2.

We also decided to migrate to nest.js.
