### ISSUE TITLE
Breaking Change since @automock/jest 1.0.1: Update Usage of @Inject Decorator with Custom Tokens

### ISSUE THREAD

**Issue by omermorad** [automock/automock#54]
Hello,

We wanted to bring your attention to a breaking change that occurred in version `1.0.1` of `@automock/jest`. Although this change was considered a breaking change, the affected API was not explicitly exposed. However, some users were utilizing this API inadvertently, causing unexpected behavior.

Previously, in version `1.0.0`, it was possible to use the `@Inject` decorator with a custom token and still reference the actual class directly. For example:

```typescript
export class NotificationService {
  constructor(@Inject('TwilioClient') private readonly twilioClient: Twilio) {}
}
```

In version `1.0.0`, some users were able to use `Twilio` class directly in the `.mock().using()` API and the `unitRef.get()` API, without explicitly using the custom token (`'TwilioClient'`), even though this behavior was not officially supported or documented.

However, in version `1.0.1`, it is necessary to use the custom token consistently in both APIs. This means that instead of using:

```typescript
.mock(Twilio)
// or
unitRef.get(Twilio)
```

You should use:

```typescript
.mock<Twilio>('TwilioClient')
// or
unitRef.get<Twilio>('TwilioClient')
```

We understand that this change may require some adjustments in your existing codebase, and we apologize for any inconvenience caused. This change was made to ensure consistent usage of custom tokens and provide clearer semantics for the injection process.

Please note that this behavior was not officially supported or documented in version `1.0.0`, and the updated behavior in version `1.0.1` aligns with the intended usage and documentation.

If you have any questions or need assistance in migrating your code to the latest version, please feel free to ask. We are here to help you.

Thank you for your understanding and continued support.

Automock Team

**Comment by GeekEast** [comment]
```
No corresponding adapter found. Please make sure to install one of the following adapters packages: nestjs. Refer to the documentation for further information: https://github.com/automock/automock#installation.
```
after installation of version `1.2.0`
