### ISSUE TITLE
Same token injected twice

### ISSUE THREAD

**Issue by pneme** [automock/automock#67]
Hello,

I was about to propose this utility to integrate into our app and run into issue in which I have same token in my service used more than once. Take a look at this:

```typescript
import { TestBed } from '@automock/jest';
import { Inject, Injectable } from '@nestjs/common';
import { v4 } from 'uuid';

@Injectable()
export class IdGenerator<T extends string> {
  generate(): T {
    return v4() as T;
  }
}

export type IdFor<T extends string> = string & T;

type FirstEntityId = IdFor<'FirstEntity'>;
type SecondEntityId = IdFor<'SecondEntity'>;

@Injectable()
class Hello {
  say(): void {
    console.log('hello');
  }
}

@Injectable()
export class FirstService {
  constructor(
    private readonly idFirstGenerator: IdGenerator<FirstEntityId>,
    private readonly idSecondGenerator: IdGenerator<SecondEntityId>,
    private readonly hello: Hello,
  ) {}

  async foo(): Promise<void> {
    console.log(this);
    this.hello.say();
  }
}

@Injectable()
export class SecondService {
  constructor(
    private readonly idFirstGenerator: IdGenerator<FirstEntityId>,
    private readonly hello: Hello,
  ) {}

  async foo(): Promise<void> {
    console.log(this);

    this.hello.say();
  }
}

it('foo 1', async () => {
  const { unit, unitRef } = TestBed.create(FirstService).compile();

  const helloModule = unitRef.get(Hello);
  const spy = jest.spyOn(helloModule, 'say');

  await unit.foo();

  expect(spy).toBeCalledTimes(1);
});

it('foo 2', async () => {
  const { unit, unitRef } = TestBed.create(SecondService).compile();

  const helloModule = unitRef.get(Hello);
  const spy = jest.spyOn(helloModule, 'say');

  await unit.foo();

  expect(spy).toBeCalledTimes(1);
});
```

**Comment by omermorad** [comment]
Hello @pneme,

Thank you for reporting this issue. I believe I have identified the problem and made the necessary changes to address it. I have released a fix in the release candidate, and I kindly request you to test the fix by installing `@automock/jest@1.2.2-rc.0`, and provide feedback on whether it resolves the problem. 

To assist with the testing process, could you please let me know which framework you are using and the version of Automock you have installed?

Thanks

**Comment by omermorad** [comment]
I noticed something unrelated to the bug that I wanted to mention. You don't actually need to use `jest.spyOn` when working with the `unitRef` object. The `unitRef` already returns a mock with all methods automatically stubbed, so instead of using `jest.spyOn` as shown in your example:

```typescript
it('foo 1', async () => {
  const { unit, unitRef } = TestBed.create(FirstService).compile();

  const helloModule = unitRef.get(Hello);
  const spy = jest.spyOn(helloModule, 'say');

  await unit.foo();

  expect(spy).toBeCalledTimes(1);
});
```

You can simplify it by directly accessing the method on the `helloModule` mock:

```typescript
it('foo 1', async () => {
  const { unit, unitRef } = TestBed.create(FirstService).compile();
  const helloModule = unitRef.get(Hello);

  await unit.foo();
  expect(helloModule.say).toBeCalledTimes(1);
});
```

This way, you can directly assert the number of times the `say` method is called without the need for `jest.spyOn`.

**Comment by omermorad** [comment]
@pneme?

**Comment by pneme** [comment]
@omermorad Hello, I was on vacation for a week.

I can confirm that issue originally reported has been resolved.
I was using Automock 1.2.1 with NestJS stack at version 9.

However I'm now still stuck due to dependency being injected in this way `@Inject(forwardRef(() => DocumentRepository))`. Automock reports that `'DocumentService' is missing a token for the dependency at index [3], did you forget to inject it using @Inject()?`. Unfortunately I was not able to isolate this for you to replicate. Do you have any ideas what that might be? Thank you! 🙏

**Comment by omermorad** [comment]
Hi @pneme,

I'm glad to hear that the original issue has been resolved. Can you provide a code snippet that shows the constructor dependencies of the relevant class under test? This will help me understand the context and provide better assistance.
