### ISSUE TITLE
Broken package types

### ISSUE THREAD

**Issue by Exeteres** [automock/automock#74]
It looks like one of the [recent commits](https://github.com/automock/automock/commit/88cbfab5980d6ba5cf13c393c524f8d5565d0e25) broke the package.
You can fix it by changing `@automock/common/src` to `@automock/common`.

![image](https://github.com/automock/automock/assets/29506045/d19e2074-e4a9-4e30-86da-5086df46a485)

**Comment by omermorad** [comment]
Hi @Exeteres,

Sorry for the inconvenience, and thanks for posting.
I applied a fix, and released version `1.2.3` (of `@automock/jest`); please try to install it and let me know if it worked for you 🙏🏻

**Comment by Exeteres** [comment]
Everything works :tada: 
Thanks for the great package!
